// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANNZklgBmuv-Td7Oc1_ZvCR5kTvrT9WmA',
    appId: '1:333528619614:web:189563ee5db0ec7973b2cf',
    messagingSenderId: '333528619614',
    projectId: 'cmsc23-group3-project',
    authDomain: 'cmsc23-group3-project.firebaseapp.com',
    storageBucket: 'cmsc23-group3-project.appspot.com',
    measurementId: 'G-09JN80F756',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMe3XMpylYGm-a3XKAtpOyoC-8ZBJc2o',
    appId: '1:333528619614:android:72279661a8348b1973b2cf',
    messagingSenderId: '333528619614',
    projectId: 'cmsc23-group3-project',
    storageBucket: 'cmsc23-group3-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlbb0q_FQ8fwnn69PBvKDVk7wuKwtL8g',
    appId: '1:333528619614:ios:429c240229d1339973b2cf',
    messagingSenderId: '333528619614',
    projectId: 'cmsc23-group3-project',
    storageBucket: 'cmsc23-group3-project.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvlbb0q_FQ8fwnn69PBvKDVk7wuKwtL8g',
    appId: '1:333528619614:ios:429c240229d1339973b2cf',
    messagingSenderId: '333528619614',
    projectId: 'cmsc23-group3-project',
    storageBucket: 'cmsc23-group3-project.appspot.com',
    iosBundleId: 'com.example.week9Authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANNZklgBmuv-Td7Oc1_ZvCR5kTvrT9WmA',
    appId: '1:333528619614:web:1a8966ddfa89ab7073b2cf',
    messagingSenderId: '333528619614',
    projectId: 'cmsc23-group3-project',
    authDomain: 'cmsc23-group3-project.firebaseapp.com',
    storageBucket: 'cmsc23-group3-project.appspot.com',
    measurementId: 'G-E0Z65XD1GF',
  );
}
